version: '3.8'

services:
  pfoaas:
    image: amitbahree/pfoaas
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: unless-stopped